import fs from 'node:fs';
const app=fs.readFileSync('public/app.js','utf8');
const html=fs.readFileSync('public/index.html','utf8');
const cfg=fs.readFileSync('public/config.js','utf8');
const p0=fs.readFileSync('public/matchday-p0-v62.js','utf8');
const p0css=fs.readFileSync('public/matchday-p0-v62.css','utf8');
const p1=fs.readFileSync('public/decision-p1-v63.js','utf8');
const p1css=fs.readFileSync('public/decision-p1-v63.css','utf8');
const p2=fs.readFileSync('public/navigation-p2-v64.js','utf8');
const p2css=fs.readFileSync('public/navigation-p2-v64.css','utf8');
const p0c=fs.readFileSync('public/p0-completion-v65.js','utf8');
const p0ccss=fs.readFileSync('public/p0-completion-v65.css','utf8');
const uiqa=fs.readFileSync('public/ui-qa-v66.css','utf8');
const p1d=fs.readFileSync('public/decision-speed-p1-v75.js','utf8');
const p1dcss=fs.readFileSync('public/decision-speed-p1-v75.css','utf8');
const checks=[];
function check(name, ok, detail=''){checks.push({name,ok,detail});if(!ok)process.exitCode=1}
check('Config has Supabase URL',/SUPABASE_URL:\s*"https:\/\//.test(cfg));
check('Config has publishable key',/SUPABASE_PUBLISHABLE_KEY:\s*"sb_publishable_/.test(cfg));
check('Public API does not misuse publishable key as Bearer',!app.includes('Authorization:`Bearer ${CFG.SUPABASE_PUBLISHABLE_KEY}`'));
check('Bootstrap loads matches first',/async function bootstrap\(\)[\s\S]*await loadMatches\(\)/.test(app));
check('Homepage stays on Match view without a selected fixture',/switchView\('match'\);[\s\S]*if\(!state\.selected\)/.test(app));
check('Navigation is not redirected to Review when no match is selected',!app.includes("if(!state.selected&&!['reviews','validation'].includes(name))name='reviews'"));
check('Pending future fixture state exists',app.includes('function renderNoUpcomingMatch()'));
check('Validation is lazy',/name==='validation'[\s\S]*loadValidation\(\)/.test(app));
check('Selected-match loader uses isolated tasks',app.includes('Promise.allSettled(tasks)'));
check('Full prediction legs are lazy',app.includes('async function ensureFullLegs()'));
check('Player thresholds load on demand',/player_id=eq\.\$\{encodeURIComponent\(playerId\)\}/.test(app));
check('Race guard present',app.includes('currentLoad(seq,matchId)'));
check('Top Edges lightweight request present',app.includes('limit=180'));
check('System Multi supports 2–5 legs',['2','3','4','5'].every(n=>app.includes(`${n}:[`)));
check('All three System Multi strategies present',['conservative','balanced','aggressive'].every(x=>app.includes(x)));
check('Match view exists',html.includes('id="view-match"'));
check('Player Markets view exists',html.includes('id="view-players"'));
check('System Multi view exists',html.includes('id="view-system-multi"'));
check('Multi Lab view exists',html.includes('id="view-multi-lab"'));
check('Field view exists',html.includes('id="view-field"'));
check('Tactics view exists',html.includes('id="view-tactics"'));
check('Validation view exists',html.includes('id="view-validation"'));
check('Shadow Live view exists',html.includes('id="view-shadow-live"'));
check('P0 Matchday CSS is linked',html.includes('matchday-p0-v62.css'));
check('P0 Matchday JS is linked',html.includes('matchday-p0-v62.js'));
check('P0 cockpit decision band exists',p0.includes('MATCHDAY COCKPIT · 10-SECOND VIEW'));
check('Probability and Confidence are separated',p0.includes('Probability = estimated outcome chance')&&p0.includes('confidenceLevel'));
check('P0 module freshness panel exists',p0.includes('DATA FRESHNESS')&&p0.includes('freshnessText'));
check('P0 cockpit exposes Top 3 player edges',p0.includes('TOP 3 EDGES')&&p0.includes('cockpitTopEdges'));
check('P0 cockpit exposes match risk summary',p0.includes('KEY RISK')&&p0.includes('matchRiskSummary'));
check('P0 cockpit has compact mobile layout',p0css.includes('.matchday-edge-quicklist')&&p0css.includes('@media(max-width:560px)'));
check('P0 removes duplicate legacy cockpit highlight strip',p0css.includes('#view-match .cockpit-highlight-strip{display:none!important}'));
check('Weather is never falsely marked fresh',p0.includes('Weather feed not connected')&&p0.includes("['Weather',{text:'Not connected'"));
check('Player WHY / RISK evidence layer exists',p0.includes('WHAT CAN BREAK IT')&&p0.includes('whyRisk'));
check('Review decision-result-learning layer exists',p0.includes('DECISION → RESULT → LEARNING')&&p0.includes('WHY WE MISSED · evidence-first'));
check('P0 responsive styles exist',p0css.includes('@media(max-width:900px)')&&p0css.includes('.matchday-decision-grid'));
check('P1 Role x Opposition CSS is linked',html.includes('decision-p1-v63.css'));
check('P1 Decision JS is linked',html.includes('decision-p1-v63.js'));
check('P1 uses existing role and opponent factors',p1.includes('role_factor')&&p1.includes('opponent_factor'));
check('P1 scenario remains explain-only',p1.includes('HEURISTIC · NOT CALIBRATED')&&p1.includes('does not mutate production probabilities'));
check('P1 scenario sensitivity exists',p1.includes('Scenario Stress Test')&&p1.includes('scenarioImpact'));
check('P1 empirical correlation UI exists',p1.includes('pair_details')&&p1.includes('Independent P')&&p1.includes('Adjusted P'));
check('P1 player WHY/RISK extension exists',p1.includes('ROLE × OPPOSITION / SCENARIO'));
check('P1 System Multi correlation risk badge exists',p1.includes('CORR RISK '));
check('P1 responsive styles exist',p1css.includes('@media(max-width:900px)')&&p1css.includes('.p1-scenario-wrap{overflow:auto}'));
check('P1 Decision Speed CSS is linked',html.includes('decision-speed-p1-v75.css'));
check('P1 Decision Speed JS is linked last',html.includes('decision-speed-p1-v75.js')&&html.indexOf('p0-completion-v65.js')<html.indexOf('decision-speed-p1-v75.js'));
check('P1 Player Ranking modes exist',['Best Edges','Confidence','Value Watch','Role Change','Injury / TOG'].every(x=>p1d.includes(x)));
check('P1 Player scanner reuses loaded state only',p1d.includes('rankedPlayers')&&p1d.includes('state.legs')&&!/\b(fetch|XMLHttpRequest|api)\s*\(/.test(p1d));
check('P1 Value Watch discloses bookmaker odds requirement',p1d.includes('真正 EV 必须输入博彩公司实际赔率后判断'));
check('P1 Role TOG risk layer exists',p1d.includes('ROLE / TOG')&&p1d.includes('latest_tog')&&p1d.includes('baseline_tog'));
check('P1 System Multi why-this-combo exists',p1d.includes('WHY THIS COMBO')&&p1d.includes('whyMulti'));
check('P1 System Multi weakest-leg exists',p1d.includes('WEAKEST LEG')&&p1d.includes('multiWeakestLeg'));
check('P1 System Multi correlation risk exists',p1d.includes('CORRELATION RISK')&&p1d.includes('correlationIntel'));
check('P1 Decision Speed does not mutate production probability',!/(model_probability\s*=|\.probability\s*=|state\.legs\s*=|state\.multis\s*=|state\.matchQuote\s*=)/.test(p1d));
check('P1 Decision Speed responsive styles exist',p1dcss.includes('@media(max-width:900px)')&&p1dcss.includes('@media(max-width:560px)'));
check('P1 mobile ranking collapses to one column',p1dcss.includes('.p1d-ranking-grid{grid-template-columns:1fr}'));
check('P2 navigation CSS is linked',html.includes('navigation-p2-v64.css'));
check('P2 navigation JS is linked',html.includes('navigation-p2-v64.js'));
check('P2 has four matchday primary routes',['match','players','system-multi','multi-lab'].every(x=>p2.includes("route:'"+x+"'"))&&p2.includes('const primary=['));
check('P2 separates System Multi and Multi Lab',p2.includes("view:'system-multi'")&&p2.includes("view:'multi-lab'")&&p2.includes("label:'SYSTEM MULTI'")&&p2.includes("label:'MULTI LAB'"));
check('P2 More keeps review research and model ops',['reviews','field','tactics','validation','shadow-live'].every(x=>p2.includes("view:'"+x+"'"))&&p2.includes("group:'Model Lab'")&&p2.includes("group:'Review & learning'"));
check('P2 Matchday flow exists',['Read Match','Find Edges','System Picks','Build Multi'].every(x=>p2.includes(x)));
check('P2 uses existing switchView',p2.includes("typeof window.switchView==='function'")&&p2.includes('window.switchView(view)'));
check('P2 mobile bottom nav is four columns',p2css.includes('grid-template-columns:repeat(4,1fr)')&&p2css.includes('env(safe-area-inset-bottom)'));
check('P2 mobile icons use explicit SVG geometry',p2.includes('xmlns="http://www.w3.org/2000/svg"')&&p2.includes('width="24" height="24" viewBox="0 0 24 24"'));
check('P2 mobile icons are Safari-safe',p2css.includes('vector-effect:non-scaling-stroke')&&p2css.includes('overflow:visible')&&p2css.includes('display:block!important'));
check('P2 mobile nav overrides premium button background',p2css.includes('#p2PrimaryNav .p2-nav-button')&&p2css.includes('background:transparent!important')&&p2css.includes('background:#e7f5ef!important'));
check('P2 More has desktop and mobile triggers',p2.includes('p2SideMore')&&p2.includes('p2HeaderMore')&&p2.includes('MORE / MODEL LAB'));
check('P2 Review is secondary not primary',p2.includes("view:'reviews'")&&!p2.includes("route:'reviews'"));
check('P2 secondary pages have return path',p2.includes('p2-secondary-more')&&p2.includes('p2-secondary-back'));
check('P2 More controls are UI-QA isolated',uiqa.includes('.p2-nav-more')&&uiqa.includes('.p2-header-more')&&uiqa.includes('.p2-secondary-more'));
check('Index has no literal newline escape text',!html.includes('\\\\n'));
check('P2 hides legacy nav only after ready',p2css.includes('body.p2-nav-ready .tabs'));
check('P2 does not mutate production probability',!/(model_probability\\s*=|\\.probability\\s*=|state\\.legs\\s*=|state\\.multis\\s*=)/.test(p2));
check('P0 completion CSS is linked',html.includes('p0-completion-v65.css'));
check('P0 completion JS is linked after P2',html.includes('p0-completion-v65.js')&&html.indexOf('navigation-p2-v64.js')<html.indexOf('p0-completion-v65.js'));
check('P0 late change uses backend observations',p0c.includes('afl_api_shadow_observations')&&p0c.includes('lineup_changed')&&p0c.includes('prediction_changed'));
check('P0 exact delta snapshot exists',p0c.includes('decision-snapshot')&&p0c.includes('compareSnapshots'));
check('P0 source and load freshness are separate',p0c.includes('SOURCE vs LOAD')&&p0c.includes('Source time unavailable'));
check('P0 weather is connected but model-safe',p0c.includes('api.open-meteo.com/v1/forecast')&&p0c.includes('INFO ONLY · NOT IN MODEL'));
check('P0 review has explicit player and multi KPIs',p0c.includes('Player markets')&&p0c.includes('System multis'));
check('P0 completion does not mutate production probability',!/(model_probability\\s*=|\\.probability\\s*=|state\\.legs\\s*=|state\\.multis\\s*=)/.test(p0c));
check('P0 completion responsive styles exist',p0ccss.includes('@media(max-width:900px)'));
check('v66 all-page UI QA layer is linked',html.includes('ui-qa-v66.css'));
check('v66 Matchday flow shows all four stages on mobile',uiqa.includes('grid-template-columns:repeat(4,minmax(0,1fr))!important')&&uiqa.includes('.p2-flow-copy small{display:none!important}'));
check('v66 P2 secondary buttons beat global green rule',uiqa.includes('.p2-multi-mode')&&uiqa.includes('.p2-drawer-item')&&uiqa.includes('.p2-secondary-back'));
check('v66 Player controls have semantic contrast',uiqa.includes('.threshold-step')&&uiqa.includes('.player-market-row .add-leg'));
check('v66 Multi Lab cards and remove controls are isolated',uiqa.includes('.match-leg-choice')&&uiqa.includes('.remove-leg'));
check('v66 Field controls preserve semantic colours',uiqa.includes('.lineup-team-filters button')&&uiqa.includes('.field-player.bench')&&uiqa.includes('.mini-player-dot.team-0'));
check('v66 Review controls are compact and clear',uiqa.includes('#reviewSelect')&&uiqa.includes('#reviewRefresh'));
check('v66 Validation tables remain readable on mobile',uiqa.includes('.validation-table th:first-child')&&uiqa.includes('position:sticky')&&uiqa.includes('-webkit-overflow-scrolling:touch'));
check('v66 Shadow timeline wraps on mobile',uiqa.includes('.shadow-step-head{flex-wrap:wrap!important'));
check('v66 supporting text gets readable mobile minimum',uiqa.includes('.note{font-size:11px!important}'));
const failed=checks.filter(x=>!x.ok);
console.log(`AFL Match Lab v75 smoke check: ${checks.length-failed.length}/${checks.length} passed`);
for(const c of checks) console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}${c.detail?' — '+c.detail:''}`);
