import fs from 'node:fs';
const app=fs.readFileSync('public/app.js','utf8');
const html=fs.readFileSync('public/index.html','utf8');
const cfg=fs.readFileSync('public/config.js','utf8');
const checks=[];
function check(name, ok, detail=''){checks.push({name,ok,detail});if(!ok)process.exitCode=1}
check('Config has Supabase URL',/SUPABASE_URL:\s*"https:\/\//.test(cfg));
check('Config has publishable key',/SUPABASE_PUBLISHABLE_KEY:\s*"sb_publishable_/.test(cfg));
check('Public API does not misuse publishable key as Bearer',!app.includes('Authorization:`Bearer ${CFG.SUPABASE_PUBLISHABLE_KEY}`'));
check('Bootstrap loads matches first',/async function bootstrap\(\)[\s\S]*await loadMatches\(\)/.test(app));
check('Validation is lazy',/name==='validation'[\s\S]*loadValidation\(\)/.test(app));
check('Selected-match loader uses isolated tasks',app.includes('Promise.allSettled(tasks)'));
check('Full prediction legs are lazy',app.includes('async function ensureFullLegs()'));
check('Player thresholds load on demand',/player_id=eq\.\$\{encodeURIComponent\(playerId\)\}/.test(app));
check('Race guard present',app.includes('currentLoad(seq,matchId)'));
check('Top Edges lightweight request present',app.includes('limit=180'));
check('System Multi supports 2–5 legs',['2','3','4','5'].every(n=>app.includes(`${n}:[`)));
check('All three System Multi strategies present',['conservative','balanced','aggressive'].every(x=>app.includes(x)));
check('Match view exists',html.includes('id="view-match"'));
check('Player Markets view exists',html.includes('id="view-players"'));
check('System Multi view exists',html.includes('id="view-system-multi"'));
check('Multi Lab view exists',html.includes('id="view-multi-lab"'));
check('Field view exists',html.includes('id="view-field"'));
check('Tactics view exists',html.includes('id="view-tactics"'));
check('Validation view exists',html.includes('id="view-validation"'));
check('Shadow Live view exists',html.includes('id="view-shadow-live"'));
const failed=checks.filter(x=>!x.ok);
console.log(`AFL Match Lab v50 smoke check: ${checks.length-failed.length}/${checks.length} passed`);
for(const c of checks) console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}${c.detail?' — '+c.detail:''}`);
